### ISSUE TITLE
(Tracking) Latest versions

### ISSUE THREAD

**Issue by Arnavion** [hexchat/gtk-win32#10]
List last updated: 2017-01-07
Packages last updated: 2016-09-06

\* Next to name indicates we mirror the tarballs

Name | Version in gtk-win32 | Latest version
- [ ] [atk\*](https://developer.gnome.org/atk/) | 2.20.0 | [2.22.0](http://ftp.gnome.org/pub/gnome/sources/atk/?C=N;O=D)
- [ ] cairo\* | 1.14.6 | [1.14.8](http://cairographics.org/releases/?C=N;O=D;P=cairo-1.*)
- [ ] enchant\* | 1.6.0 | [1.6.1](https://github.com/AbiWord/enchant/releases)
- [ ] fontconfig\* | 2.8.0 | [2.12.1](http://www.freedesktop.org/software/fontconfig/release/?C=N;O=D)
- [ ] freetype\* | 2.6.5 | [2.7.1](https://download.savannah.gnu.org/releases/freetype/?C=N;O=D;P=freetype-2.*)
- [ ] [gdk-pixbuf\*](https://developer.gnome.org/gdk-pixbuf/) | 2.34.0 | [2.36.3](http://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/?C=N;O=D)
- [ ] gettext\* | 0.18 | [0.18](http://winkde.org/pub/kde/ports/win32/repository-4.8/win32libs/?P=gettext*-src*) / [0.19.8.1](http://ftp.gnu.org/gnu/gettext/?C=M;O=D)
- [ ] [glib\*](https://developer.gnome.org/glib/) | 2.48.2 | [2.50.2](http://ftp.gnome.org/pub/gnome/sources/glib/?C=N;O=D)
- [ ] [gobject-introspection\*](https://developer.gnome.org/gi/stable/) | 1.48.0 | [1.50.0](http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/?C=N;O=D;P=1.*)
- [ ] [gtk\*](https://developer.gnome.org/gtk2/) | 2.24.30 | [2.24.31](http://ftp.gnome.org/pub/gnome/sources/gtk+/?C=N;O=D;P=2.*)
- [ ] harfbuzz\* | 1.3.0 | [1.4.1](https://www.freedesktop.org/software/harfbuzz/release/?C=N%3bO=D)
- [x] lgi\* | 0.9.1 | [0.9.1](https://github.com/pavouk/lgi/releases)
- [x] libffi\* | 3.2.1 | 3.2.1 ftp://sourceware.org/pub/libffi/
- [ ] libpng\* | 1.6.25 | [1.6.28](http://www.libpng.org/pub/png/libpng.html)
- [x] libxml2\* | 2.9.4 | 2.9.4 ftp://xmlsoft.org/libxml2/
- [x] luajit\* | 2.0.4 | [2.0.4](http://luajit.org/download.html)
- [ ] openssl\* | 1.0.2h | [1.0.2j / 1.1.0c](https://www.openssl.org/source/)
- [ ] [pango\*](https://developer.gnome.org/pango/) | 1.40.2 | [1.40.3](http://ftp.gnome.org/pub/gnome/sources/pango/?C=N;O=D)
- [x] pixman\* | 0.34.0 | [0.34.0](http://cairographics.org/releases/?C=N;O=D;P=pixman-*)
- [x] pkg-config | 0.29.1 | [0.29.1](https://pkg-config.freedesktop.org/releases/)
- [x] win-iconv\* | 0.0.8 | [0.0.8](https://github.com/win-iconv/win-iconv/releases)
- [ ] zlib\* | 1.2.8 | [1.2.10](http://zlib.net/)
- [ ] [openssl certdata.txt](https://hg.mozilla.org/mozilla-central/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt) | 2016-08-30 | [2016-09-23](https://hg.mozilla.org/mozilla-central/log/default/security/nss/lib/ckfw/builtins/certdata.txt)

Note: Ignore odd-numbered minor versions of atk, gdk-pixbuf, glib, gobject-introspection, gtk and pango because these are development releases.

Versions in latest HexChat release (2.12.0)

<table>
    <thead><tr><th>Name</th><th>Version</th></tr></thead>
    <tbody>
        <tr><td>atk</td><td>2.18.0</td></tr>
        <tr><td>cairo</td><td>1.14.6</td></tr>
        <tr><td>enchant</td><td>1.6.0</td></tr>
        <tr><td>fontconfig</td><td>2.8.0</td></tr>
        <tr><td>freetype</td><td>2.6.3</td></tr>
        <tr><td>gdk-pixbuf</td><td>2.32.3</td></tr>
        <tr><td>gettext-runtime</td><td>0.18</td></tr>
        <tr><td>glib</td><td>2.46.2</td></tr>
        <tr><td>gtk</td><td>2.24.30</td></tr>
        <tr><td>harfbuzz</td><td>1.2.3</td></tr>
        <tr><td>libffi</td><td>3.2.1</td></tr>
        <tr><td>libpng</td><td>1.6.21</td></tr>
        <tr><td>openssl</td><td>1.0.2g</td></tr>
        <tr><td>pango</td><td>1.39.0</td></tr>
        <tr><td>pixman</td><td>0.34.0</td></tr>
        <tr><td>win-iconv</td><td>0.0.8</td></tr>
        <tr><td>zlib</td><td>1.2.8</td></tr>
        <tr><td>openssl certdata.txt</td><td>2016-02-26</td></tr>
    </tbody>
</table>

<img src="http://hexchat.github.io/gtk-win32/img/dependency-graph.png">

**Comment by nacho** [comment]
Here some update on the last versions

glib = 2.46.0
gdk-pixbuf = 2.32.0
cairo = 1.14.2
atk = 2.18.0
gtk = 2.24.28
pango = 1.38.0

**Comment by nacho** [comment]
About gettext-runtime. We could use Fan's project https://github.com/fanc999/gtk-msvc-projects/tree/master/gettext/0.19.4 which apart from giving us an updated gettext it would mean to have intl.lib instead of libintl.lib so it would be less work later to update the projects.
